version: '3'
services:
  postgresql:
    image: postgres
    container_name: postgresql
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres